TST: add package linking a library from a subproject
Note that for Meson versions older than 1.2.0, CI failed with:
```
mesonpy.BuildError: Could not map installation path to an equivalent wheel directory: '{libdir_static}/libexamplelib.a'
```
because the `--skip-subprojects` install option isn't honored.
Hence the test skip on older versions.

In addition, the `c_shared_libs` usage requires Meson 1.3.0

- meson-python commit 2a9179d86c488d27e9614dcfdd082cc8668572e2